kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo-bar
spec:
  containers:
  - name: foo-app
    image: docker.io/ehtesham12/foo-bar:latest
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo-bar
  ports:
  - port: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: foo-service
            port:
              number: 8080
---
